#!/bin/bash
# created and maintained by
# ragon <frederik.engels24@gmail.com>

. /etc/rc.conf
. /etc/rc.d/functions

java_flags="-server -XX:ParallelGCThreads=3 -Xmn230M -Xmx1560M -Xms1560M"
config_dir=/srv/bukkit/
world_dir=world_hoth
backup_dir=/srv/bukkit/backups/
cp_format=$(date '+%Y%m%dh%Hm%M')
profile_dir=/etc/profile.d/

craft_dir=/srv/bukkit/bin/
craft_jar=craftbukkit-1.0.0-SNAPSHOT.jar

bukkit_dir=/srv/bukkit/bin/
bukkit_jar=bukkit-1.9-pre5-R1-SNAPSHOT.jar

java_bin=/opt/java/bin/java
maven_bin=/opt/maven/bin/mvn

_gitlocal=/usr/src/Bukkit/
_gitlocal2=/usr/src/CraftBukkit/

_gitweb=git://github.com/Bukkit/Bukkit.git
_gitweb2=git://github.com/Bukkit/CraftBukkit.git

check_dir()
{
	if [ -d $craft_dir ] ; then
		sleep 0
	else
		mkdir -p $craft_dir
	fi
	if [ -d $bukkit_dir ] ; then
		sleep 0
	else
		mkdir -p $bukkit_dir
	fi
}
function run_as() {
	su mc -c "$1"
}

case "$1" in
	start)
		stat_busy "starting Bukkit Server"
		check_dir
		if  [ "$(screen -ls | grep bukkit)" == "" ] ; then
			cd $config_dir
			screen -S bukkit -dmS su mc -c "$java_bin $java_flags -jar $craft_dir$craft_jar"
			add_daemon bukkit
			stat_done
		else	
			echo "bukkit server already running"
			stat_fail
			exit 0
		fi
		if [ -d $config_dir ] ; then
			sleep 0
		else
			mkdir -p $config_dir
		fi
		;;
	stop)
		stat_busy "stopping Bukkit Server"
		check_dir
		if [ "$(screen -ls | grep bukkit)" == "" ] ; then
			echo "bukkit server is not running"
                        stat_fail
			exit 0
		else
			screen -S bukkit -p 0 -X stuff "stop$(echo -ne '\r')"
                        sleep 5
			killall screen
			killall java
                        rm_daemon bukkit
                        stat_done

		fi
		;;
	restart) 
		
		$0 stop
		sleep 5 # give enough time to shutdown and close screen
		$0 start
		;;
	send)
		check_dir
		if [ "$(screen -ls | grep bukkit)" == "" ] ; then
			echo "bukkit server is not running"
			exit 0
		else
			if [ $2 != "" ]; then
				screen -S bukkit -p 0 -X stuff "$2$(echo -ne '\r')"
			else
				echo "Nothing do do"
			fi
		fi
		;;
	upgrade)
		stat_busy "stopping Bukkit Server"
		check_dir
		if  [ "$(screen -ls | grep bukkit)" == "" ] ; then
			sleep 0
		else
			screen -S bukkit -p 0 -X stuff "say server shutting down in 60 seconds for upgrade$(echo -ne '\r')"
                        sleep 30
			screen -S bukkit -p 0 -X stuff "say server shutting down in 30 seconds$(echo -ne '\r')"
			sleep 20
			screen -S bukkit -p 0 -X stuff "say 10$(echo -ne '\r')"
			sleep 5
			screen -S bukkit -p 0 -X stuff "say 5$(echo -ne '\r')"
			sleep 1
			screen -S bukkit -p 0 -X stuff "say 4$(echo -ne '\r')"
			sleep 1
			screen -S bukkit -p 0 -X stuff "say 3$(echo -ne '\r')"
			sleep 1
			screen -S bukkit -p 0 -X stuff "say 2$(echo -ne '\r')"
			sleep 1
			screen -S bukkit -p 0 -X stuff "say 1$(echo -ne '\r')"
			sleep 1
                        screen -S bukkit -p 0 -X stuff "stop$(echo -ne '\r')"
                        rm_daemon bukkit
		fi

		echo "upgrading server now"
		if [ -d "$_gitlocal" ] ; then
			cd "$_gitlocal" && git pull
		else
			mkdir -p "$_gitlocal"
			cd "$_gitlocal/../"
			git clone $_gitweb
		fi
		
		cd $_gitlocal
		if [ -f "$profile_dir/jdk.sh" ] ; then
			source $profile_dir/jdk.sh
		fi
		$maven_bin clean install
				
		cp $_gitlocal/target/$bukkit_jar $bukkit_dir

		if [ -d "$_gitlocal2" ] ; then
			cd "$_gitlocal2" && git pull
		else 
			mkdir -p "$_gitlocal2"
			cd "$_gitlocal2/../"
			git clone $_gitweb2
		fi
		
		cd $_gitlocal2
		$maven_bin clean package
		
		cp $_gitlocal2/target/$craft_jar $craft_dir
		
		stat_done
		;;

	slowstop) ## be friendly to your players :)
		
		stat_busy "stopping Bukkit Server"
		check_dir
                if [ "$(screen -ls | grep bukkit)" == "" ] ; then
			sleep 0
                else
			screen -S bukkit -p 0 -X stuff "say server shutting down in 60 seconds for system upgrade$(echo -ne '\r')"
                        sleep 30
			screen -S bukkit -p 0 -X stuff "say server shutting down in 30 seconds$(echo -ne '\r')"
			sleep 20
			screen -S bukkit -p 0 -X stuff "say 10$(echo -ne '\r')"
			sleep 5
			screen -S bukkit -p 0 -X stuff "say 5$(echo -ne '\r')"
			sleep 1
			screen -S bukkit -p 0 -X stuff "say 4$(echo -ne '\r')"
			sleep 1
			screen -S bukkit -p 0 -X stuff "say 3$(echo -ne '\r')"
			sleep 1
			screen -S bukkit -p 0 -X stuff "say 2$(echo -ne '\r')"
			sleep 1
			screen -S bukkit -p 0 -X stuff "say 1$(echo -ne '\r')"
			sleep 1
                        screen -S bukkit -p 0 -X stuff "stop$(echo -ne '\r')"
                        rm_daemon bukkit

		fi
		stat_done
		;;
	status)
		stat_busy 'Checking Bukkit server status'
                ck_status bukkit
                ;;
	backup)
		stat_busy "backing up Bukkit world"
		
		check_dir
		if [ "$(screen -ls | grep bukkit)" == "" ] ; then
			sleep 0
		else
                       	sleep 5
		fi
		if [ -d $backup_dir ] ; then
			sleep 0
		else
			mkdir -p $backup_dir
		fi
		echo "backing up as $backup_dir$world_dir"

		cd $config_dir

		rdiff-backup $world_dir $backup_dir$world_dir

		if [ "$(screen -ls | grep bukkit)" == "" ] ; then
                        sleep 0
                else
			screen -S bukkit -p 0 -X stuff "say World Backed Up Succesfully!$(echo -ne '\r')"
                fi
		stat_done
		;;
	*)
		echo "usage: $0 {start|stop|restart|status|upgrade|sysupgrade|backup}"
esac

exit 0

